export { default as AboutPage } from './about'
export { default as MediaPage } from './media'
export { default as EstimatorPage } from './estimator'
export { default as HomePage } from './home'
export { default as BlogPage } from './blogs'
export { default as ProjectsPage } from './projects'
export { default as NotFoundPage } from './404Page'